In [3]:
#import
import pandas as pd
import numpy as np

In [4]:
#load data
customers= pd.read_csv("C:/Users/DELL/OneDrive/Documents/samsung project/customers (1).csv")
products= pd.read_csv("C:/Users/DELL/OneDrive/Documents/samsung project/products (1).csv")
orders= pd.read_csv("C:/Users/DELL/OneDrive/Documents/samsung project/orders (1).csv")
order_items= pd.read_csv("C:/Users/DELL/OneDrive/Documents/samsung project/order_items (1).csv")

In [15]:
print("customer_table\n",customers.head())
print("product_table\n",products.head())

customer_table
    customer_id              name                       email country  age  \
0            1  Jennifer Salinas      nicholas59@example.org      JP   71
1            2     Phillip Ramos  christinarubio@example.com      IN   26
2            3       Dawn Fowler       jessica03@example.org      BR   21
3            4      Mario Butler         paula27@example.org      FR   63
4            5       Amber Brown         kevin85@example.net      BR   19

  signup_date  marketing_opt_in
0  2020-09-04              True
1  2020-04-05             False
2  2023-08-31              True
3  2022-06-30              True
4  2022-07-22              True
product_table
    product_id     category                      name  price_usd  cost_usd  \
0           1  Electronics        SSD MediumBlue 149     570.28    352.69
1           2  Electronics     Keyboard DeepPink 696     498.13    263.13
2           3  Electronics     Headphones Orchid 188     548.53    309.60
3           4  Electronics  Smartwatch BurlyWood 664     268.36    153.56
4           5  Electronics   Smartwatch Cornsilk 328      63.69     42.65

   margin_usd
0      217.59
1      235.00
2      238.93
3      114.80
4       21.04

In [16]:
print("orders_table\n",orders.head())
print("order_items_table\n",order_items.head())

orders_table
    order_id  customer_id           order_time payment_method  discount_pct  \
0         1        13917  2025-01-31T23:07:42           card            20
1         2         1022  2024-02-19T01:17:50           card             0
2         3         6145  2024-12-04T20:24:13           card             0
3         4         3152  2024-07-17T08:50:47           card            15
4         5        12378  2020-08-21T16:54:16           card             0

   subtotal_usd  total_usd country   device   source
0        107.15      85.72      PL  desktop  organic
1        116.17     116.17      FR   tablet  organic
2        137.35     137.35      US   mobile  organic
3         32.18      27.35      BR   mobile    email
4        238.09     238.09      NL  desktop     paid
order_items_table
    order_id  product_id  unit_price_usd  quantity  line_total_usd
0         1         226          107.15         1          107.15
1         2         771          116.17         1          116.17
2         3         415           94.49         1           94.49
3         3          24           42.86         1           42.86
4         4        1157           32.18         1           32.18

In [26]:
print('columns ', list(customers.columns))
print('shape ', customers.shape)
print('columns ', list(products.columns))
print('shape ', products.shape)
print('columns ', list(orders.columns))
print('shape ', orders.shape)
print('columns ', list(order_items.columns))
print('shape ', order_items.shape)

columns  ['customer_id', 'name', 'email', 'country', 'age', 'signup_date', 'marketing_opt_in']
shape  (20000, 7)
columns  ['product_id', 'category', 'name', 'price_usd', 'cost_usd', 'margin_usd']
shape  (1197, 6)
columns  ['order_id', 'customer_id', 'order_time', 'payment_method', 'discount_pct', 'subtotal_usd', 'total_usd', 'country', 'device', 'source']
shape  (33580, 10)
columns  ['order_id', 'product_id', 'unit_price_usd', 'quantity', 'line_total_usd']
shape  (59163, 5)

In [25]:
print(customers.info())
print(products.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       20000 non-null  int64
 1   name              20000 non-null  object
 2   email             20000 non-null  object
 3   country           20000 non-null  object
 4   age               20000 non-null  int64
 5   signup_date       20000 non-null  object
 6   marketing_opt_in  20000 non-null  bool
dtypes: bool(1), int64(2), object(4)
memory usage: 957.2+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1197 entries, 0 to 1196
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product_id  1197 non-null   int64
 1   category    1197 non-null   object
 2   name        1197 non-null   object
 3   price_usd   1197 non-null   float64
 4   cost_usd    1197 non-null   float64
 5   margin_usd  1197 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 56.2+ KB
None

In [23]:
print(orders.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33580 entries, 0 to 33579
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        33580 non-null  int64
 1   customer_id     33580 non-null  int64
 2   order_time      33580 non-null  object
 3   payment_method  33580 non-null  object
 4   discount_pct    33580 non-null  int64
 5   subtotal_usd    33580 non-null  float64
 6   total_usd       33580 non-null  float64
 7   country         33580 non-null  object
 8   device          33580 non-null  object
 9   source          33580 non-null  object
dtypes: float64(2), int64(3), object(5)
memory usage: 2.6+ MB
None

In [22]:
print(order_items.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59163 entries, 0 to 59162
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        59163 non-null  int64
 1   product_id      59163 non-null  int64
 2   unit_price_usd  59163 non-null  float64
 3   quantity        59163 non-null  int64
 4   line_total_usd  59163 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 2.3 MB
None

In [32]:
print(customers.describe())
print(products.describe())

        customer_id           age
count  20000.000000  20000.000000
mean   10000.500000     46.492550
std     5773.647028     16.767961
min        1.000000     18.000000
25%     5000.750000     32.000000
50%    10000.500000     46.500000
75%    15000.250000     61.000000
max    20000.000000     75.000000
        product_id    price_usd     cost_usd   margin_usd
count  1197.000000  1197.000000  1197.000000  1197.000000
mean    599.000000   119.935171    77.626483    42.308688
std     345.688444   119.681742    79.228858    44.464057
min       1.000000     3.500000     2.210000     1.030000
25%     300.000000    38.540000    23.530000    12.240000
50%     599.000000    77.200000    49.140000    27.020000
75%     898.000000   165.420000   103.670000    55.440000
max    1197.000000   596.620000   446.100000   263.730000

In [31]:
print(orders.describe())
print(order_items.describe())

           order_id   customer_id  discount_pct  subtotal_usd     total_usd
count  33580.000000  33580.000000  33580.000000  33580.000000  33580.000000
mean   16790.500000  10010.629899      7.160214    144.002627    133.806357
std     9693.855356   5798.458913      7.474901    162.603585    152.130611
min        1.000000      1.000000      0.000000      3.500000      2.800000
25%     8395.750000   4964.000000      0.000000     44.060000     40.300000
50%    16790.500000  10008.000000      5.000000     93.620000     86.460000
75%    25185.250000  15061.000000     15.000000    187.100000    174.270000
max    33580.000000  19999.000000     20.000000   3141.660000   2984.580000
           order_id    product_id  unit_price_usd      quantity  \
count  59163.000000  59163.000000    59163.000000  59163.000000
mean   16811.777868    692.100147       62.837561      1.303281
std     9687.818391    329.197199       62.061297      0.786787
min        1.000000      1.000000        3.500000      1.000000
25%     8454.000000    411.000000       21.640000      1.000000
50%    16838.000000    738.000000       44.650000      1.000000
75%    25203.000000    980.000000       79.450000      1.000000
max    33580.000000   1197.000000      596.620000      4.000000

       line_total_usd
count    59163.000000
mean        81.733655
std        106.360939
min          3.500000
25%         24.770000
50%         49.920000
75%         98.680000
max       2376.920000

In [27]:
print(customers.duplicated().sum())
print(products.duplicated().sum())
print(orders.duplicated().sum())
print(order_items.duplicated().sum())

0
0
0
73

In [ ]:
print(customers.isnull().sum())
print(products.isnull().sum())

customer_id         0
name                0
email               0
country             0
age                 0
signup_date         0
marketing_opt_in    0
dtype: int64
product_id    0
category      0
name          0
price_usd     0
cost_usd      0
margin_usd    0
dtype: int64
order_id          0
customer_id       0
order_time        0
payment_method    0
discount_pct      0
subtotal_usd      0
total_usd         0
country           0
device            0
source            0
dtype: int64
order_id          0
product_id        0
unit_price_usd    0
quantity          0
line_total_usd    0
dtype: int64

In [34]:
print(orders.isnull().sum())
print(order_items.isnull().sum())

order_id          0
customer_id       0
order_time        0
payment_method    0
discount_pct      0
subtotal_usd      0
total_usd         0
country           0
device            0
source            0
dtype: int64
order_id          0
product_id        0
unit_price_usd    0
quantity          0
line_total_usd    0
dtype: int64

In [ ]:
#invalid value in customers
print(customers[customers["age"] < 0])
print(customers[customers["email"].isna() | (customers["email"].str.strip() == "")])
print(customers[~customers["marketing_opt_in"].isin([True, False])])

Empty DataFrame
Columns: [customer_id, name, email, country, age, signup_date, marketing_opt_in]
Index: []
Empty DataFrame
Columns: [customer_id, name, email, country, age, signup_date, marketing_opt_in]
Index: []
Empty DataFrame
Columns: [customer_id, name, email, country, age, signup_date, marketing_opt_in]
Index: []

In [ ]:
#invalid value in product
print(products[products["price_usd"] < 0])
print(products[products["cost_usd"] < 0])
#check categories in product
print(products["category"].value_counts(dropna=False))

Empty DataFrame
Columns: [product_id, category, name, price_usd, cost_usd, margin_usd]
Index: []
Empty DataFrame
Columns: [product_id, category, name, price_usd, cost_usd, margin_usd]
Index: []
category
Electronics       171
Home & Kitchen    171
Beauty            171
Sports            171
Fashion           171
Books             171
Toys              171
Name: count, dtype: int64

In [40]:
#invalid value in product
products[
    products["margin_usd"] !=
    (products["price_usd"] - products["cost_usd"])
]

,product_id,category,name,price_usd,cost_usd,margin_usd
0,1,Electronics,SSD MediumBlue 149,570.28,352.69,217.59
2,3,Electronics,Headphones Orchid 188,548.53,309.60,238.93
3,4,Electronics,Smartwatch BurlyWood 664,268.36,153.56,114.80
7,8,Electronics,Mouse Moccasin 673,338.19,227.02,111.17
8,9,Electronics,Mouse Chartreuse 292,88.74,59.58,29.16
...,...,...,...,...,...,...
1189,1190,Toys,Board Game Wheat 727,55.71,44.29,11.42
1190,1191,Toys,Puzzle BurlyWood 196,46.41,28.11,18.30
1193,1194,Toys,Action Figure Turquoise 442,16.94,11.55,5.39
1195,1196,Toys,Building Blocks LightCoral 517,21.83,13.44,8.39
1196,1197,Toys,Building Blocks WhiteSmoke 876,48.51,27.32,21.19

In [ ]:
#invalid in orders
print(orders[orders["discount_pct"] < 0])
print(orders[orders["discount_pct"] > 100])
print(orders[orders["subtotal_usd"] < 0])
print(orders[orders["total_usd"] < 0])

Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []
Empty DataFrame
Columns: [order_id, customer_id, order_time, payment_method, discount_pct, subtotal_usd, total_usd, country, device, source]
Index: []

In [46]:
#check in orders col
print(orders["payment_method"].value_counts(dropna=False))
print(orders["device"].value_counts(dropna=False))
print(orders["source"].value_counts(dropna=False))

payment_method
card      23455
paypal     5032
wallet     3373
cod        1720
Name: count, dtype: int64
device
mobile     18469
desktop    12750
tablet      2361
Name: count, dtype: int64
source
organic     11268
direct       8387
paid         4121
social       4024
email        3056
referral     2724
Name: count, dtype: int64

In [ ]:
#invalid in order_items
print(order_items[order_items["quantity"] < 0])
print(order_items[order_items["quantity"] == 0])
print(order_items[order_items["unit_price_usd"] < 0])
print(order_items[order_items["line_total_usd"] < 0])

Empty DataFrame
Columns: [order_id, product_id, unit_price_usd, quantity, line_total_usd]
Index: []
Empty DataFrame
Columns: [order_id, product_id, unit_price_usd, quantity, line_total_usd]
Index: []
Empty DataFrame
Columns: [order_id, product_id, unit_price_usd, quantity, line_total_usd]
Index: []
Empty DataFrame
Columns: [order_id, product_id, unit_price_usd, quantity, line_total_usd]
Index: []

In [ ]:
#invalid 
order_items[
    order_items["line_total_usd"] !=
    (order_items["unit_price_usd"] * order_items["quantity"])
]

       order_id  product_id  unit_price_usd  quantity  line_total_usd
18           11        1021           18.59         3           55.77
103          60         284          159.05         3          477.15
149          86         291           83.49         3          250.47
159          91        1043            8.79         3           26.37
226         131        1051           11.03         3           33.09
...         ...         ...             ...       ...             ...
58597     33273         192          196.45         3          589.35
58626     33287         899           14.03         3           42.09
58812     33387         869            9.20         3           27.60
58882     33430         846           39.60         3          118.80
59031     33509         476           29.44         3           88.32

[872 rows x 5 columns]